### ISSUE TITLE
1 - Day 01 - Milestone: Getting the data

### ISSUE THREAD

**Issue by giumr06** [btorres1993/ML-Frauddetection#3]
- [x]  Get data
- [x]  merge the tables via client_id
- [x] choose which columns to keep and drop the leftovers
- [x] load the data in our notebook
